---
install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.57.2/hugo_0.57.2_Linux-64bit.deb
- sudo dpkg -i hugo_0.57.2_Linux-64bit.deb

script:
- hugo

deploy:
- provider: pages
  skip-cleanup: true
  local-dir: public
  github-token: $GITHUB_TOKEN
  keep-history: false
