ignoreFiles = [
    "content/draft"
]

baseURL = "https://blog.indexyz.me/"
title = "Indexyz Blog"
author = "Indexyz"
copyright = "Copyright © 2018-{year}, Indexyz"
paginate = 8

theme = "hugo-theme-index"

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=inline"

disableKinds = ["taxonomyTerm"]

[taxonomies]
  category = "categories"

[params]
    description = "Sharing light, even in death"
    disqusEnable = true
    [params.disqusConfig]
        shortname = "indexyz-blog"
        siteName = "Indexyz Blog"
        api = "https://disqus.skk.moe/disqus/"
        apikey = "VtpQwhbhO3YTIYSZdx1N8vOJ6me3une1xSIeXhpuPcE4jurE17UlJozkc9qhvjDw"
    [params.analytics]
        type = "gtag"
        id = "UA-97074604-1"

[menu]
    [[menu.main]]
        identifier = "index"
        name = "首页"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "friends"
        name = "友链"
        url = "/friends/"
        weight = 2

[permalinks]
    posts = "/archives/:filename"
